#defines which scripts needs to be run
#generate - performs templating & kustomization
#deploy   - apply's the generated script in k8s environment
scripts: generate deploy
#defines applications needed. Monitor installed by default.
#Secure is optional. Remove secure if not.
apps: monitor secure
#Size of the cluster. Takes [ small | medium | large ]
#This defines CPU & Memory & Disk & Replicas
#Replicas can be overwritten for medium , large in advanced   config section
size: medium
#Set k8s namespace for sysdigcloud
namespace: sysdigcloud
#Set Quay.Io secrets
quaypullsecret: <Insert QuaySecret>
#StorageClass config
storageClassName: <Insert StorageClassName>
#This drives multi-az awareness, if sysdigcloud is deployed to a multi-az setup
#this should be updated as adequate
cloudProvider:
  # example aws
  name:
  # boolean true|false
  isMultiAZ: false
  # example us-east-1
  region: ""
#supports aws | gke | hostPath
#Do not use hostPath in production, currently it is experimental only.
storageClassProvisioner: aws
#supports openshift | kubernetes defaults to kubernetes install
deployment: kubernetes
#Sysdig application config
sysdig:
  agentCount: 10
  #Set Sysdig license
  license: <Insert SysdigLicense>
  dnsName: <Insert DNS Name>
  monitorVersion: 2304
  anchoreVersion: v0.3.4.1
  #Advanced settings
  #autogenerate certificate by default - generate to
  #false and provide crt,key to use existing certs, make
  #sure the key and cert are in your current working
  #directory
  certificate:
    generate: true
    crt:
    key:
  #replicas settings
  #default replicas are set based on size - small, medium & large
  #below section acts as a override
  cassandraReplicaCount:
  elasticSearchReplicaCount:
  apiReplicaCount:
  collectorReplicaCount:
  workerReplicaCount:
  anchoreCoreReplicaCount:
  anchoreWorkerReplicaCount:
  scanningApiReplicaCount:
  scanningAlertMgrReplicaCount:
  #set to true for highly available redis
  redisHa: false
  #SMTP Configurations
  smtpServer: ""
  smtpServerPort: "25"
  #User,Password can be empty if the server does not require authentication
  smtpUser: ""
  smtpPassword: ""
  smtpProtocolTLS: "false"
  smtpProtocolSSL: "false"
  #Optional Email Header
  smtpFromAddress: ""
  #Please provide openshift parameters
  openshiftUrl:
  openshiftUsername:
  openshiftPassword:
  #Override for default collector port
  #defaults to 6443
  collectorPort:
