#Set k8s namespace for sysdigcloud
namespace: sysdigcloud-pj-template
#Set Quay.Io secrets
quaypullsecret: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM2x6WkdsbkszQnlZWFpwYm1wdmRHaHBibUYwYUdGdU9rOUROekUwTmtneFdsZFdNVVpZUmxaTlRrYzNOa2xWUVZSSE1VaFNRMFpOTUZoUFJUWlFSemxGT0VoRFNsSmFVelJETXpCVlZVY3dUVFZMUmxGSVJWRT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
#Set Sysdig license
sysdig:
  license: 61689bdaaaa0abed294ef2d446ddf6af25cb3669bdd24f7dfa04f75f1598d56ceabaa5aaf4cb18256bf01b0071e53f838df7d939dae960eed31efa809369ae14ffde60ddd2b21244772b46febfd117e198bbdaa612a21f8b37bbc123140f2ca74ad92c3e30afde2350463a2a7dc0a4373caf107d38438d498029f6dad6dde21c1c068c453e106296005e4d7f436cc89defe7b1681bbb8b70c4a2ed1de838ba54b9d9fcce8c2c09d51732e2e34a8ef213aba56746abbf14038d93cd77ba63f27d101f0b372baa444fa89519ffa7d3eea6
  default:
    username: test@sysdig.com
    password: RandomGeneratedSysdigPassword
  mysql:
    username: mysql-admin
    password: RandomGeneratedMySqlPassword
    root:
      password: RandomGeneratedMySqlRootPassword
    secure:
      password: RandomGeneratedMySqlSecurePassword
  redis:
    password: RandomGeneratedRedisPassword
  storageclass:
    name: pj-gp2-retain
  endpoint: aa2ca63f362ea11e9a0710a2da0e6c53-896137843.us-east-1.elb.amazonaws.com
  secure:
    admin:
      password: RandomGeneratedSecureAdminPassword
    db:
      password: RandomGeneratedSecurePassword

#machines #of nodes, cpu/mem
#agents 
#do we need secure?
#replicas - pods #cassy #elastic
#cpu #memory #disk
