---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  labels:
    app: sysdigcloud
    role: redis
spec:
  ports:
    - port: 6379
  selector:
    app: sysdigcloud
    role: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-redis
spec:
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: redis
    spec:
      containers:
        - name: redis
          image: quay.io/sysdig/redis:3.2.12.5-alpine
          resources:
            requests:
              memory: "4G"
              cpu: "1"
            limits:
              memory: "4G"
              cpu: "1"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: redis.password
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      nodeSelector:
        kops.k8s.io/instancegroup: storage-nodes
